/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop.lab.week5;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class AppTest {


}
